engines:
  eslint:
    enabled: true
    channel: "eslint-2"

  duplication:
    enabled: true
    config:
      languages:
        - javascript

  nodesecurity:
    enabled: true

ratings:
  paths:
    - "**.js"
    - "**.css"

exclude_paths:
  - "frontendTest/lib/"
  - "node_modules/"
